name: SecureBot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up MSBuild for .NET Framework 4.8 WPF build
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    # Optional: List files for debugging paths
    - name: List files in repository
      run: dir

    # Restore NuGet packages if you use them
    - name: Restore NuGet packages
      run: nuget restore SecureBot.sln

    # Build the solution in Release mode
    - name: Build solution
      run: msbuild SecureBot.sln /p:Configuration=Release


   

